### ISSUE TITLE
No module named 'xhtml2pdf'

### ISSUE THREAD

**Issue by ramz35** [dakshesh14/anukool#1]
Following the instructions and running main.py I got:

Traceback (most recent call last):
  File "C:\Repository\Coding\GenerativeAI\anukool\main.py", line 13, in <module>
    from helper import load_environment, load_model, render_to_pdf
  File "C:\Repository\Coding\GenerativeAI\anukool\helper.py", line 13, in <module>
    from xhtml2pdf import pisa
ModuleNotFoundError: No module named 'xhtml2pdf'

pip install xhtml2pdf gets rid of this error so perhaps an update to requirements.txt?

**Comment by dakshesh14** [comment]
I assume you already have the environment setup and that this issue is coming because I forgot to freeze xhtml2pdf in `requirements.txt`. I have pushed the change for it. You can pull the latest changes and check if you are still getting the same error after reinstalling from `requirements.txt`.

Please let me know if the error persists.

**Comment by ramz35** [comment]
I already fixed it by pip installing so was just letting you know.

**Comment by dakshesh14** [comment]
Yep, I read your comment just now. I got carried away without reading your comment since this was the first raised issue in this project 😅.

**Comment by dakshesh14** [comment]
Fixed in [commit](https://github.com/dakshesh14/anukool/commit/7ddd3dad1f10e78ef034f171d23a4759be47bf80)

**Comment by ramz35** [comment]
I have a few more ;) and will post later today.
